module.exports.User = {
    "name": "Roly",
    "screen_name": "RolyUnGashaa",
    "description": "LGBT+ Advocate & YouTube Video Creator living in London! 27, Non-Binary & Body Modification enthusiast 🌈 Business: rolyungashaahd@gmail.com",
    "location": "London, England",
    "protected": false,
    "followers_count": 22872,
    "friends_count": 486,
    "created_at": "Wed Oct 21 20:16:41 +0000 2009",
    "favourites_count": 32003,
    "verified": true,
    "statuses_count": 34168,
    "profile_image_url_https": "https://pbs.twimg.com/profile_images/907749648135225345/9Ea67ocj_400x400.jpg",
    "profile_banner_url": "https://pbs.twimg.com/profile_banners/84152649/1503609450",
    "usersFollowers": [
        {
            "name": "いせやん🐟ウオタミ≫UUUM大好き!!",
            "screen_name": "iseyan_uotami",
            "description": "Fischer's/スカイピース/アバンティーズ/水溜りボンド/おるたな/CB/すしりく/東海オンエア/相方↪︎@ruka_silk 安定↪︎@misakroad_71相棒↪︎@m320_silk819 同盟🐼#シルだほ同盟#シルマサ同盟#シルペケ同盟#きぬたみ同盟#アラサー同盟#安定同盟#ヒトエタラコザル同盟",
            "location": "Fischer's教 No.5 ウオタミ住民No.88",
            "protected": false,
            "followers_count": 4096,
            "friends_count": 3513,
            "created_at": "Thu May 18 10:41:22 +0000 2017",
            "favourites_count": 2423,
            "verified": false,
            "statuses_count": 7839,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/902705633039859712/1DH3ZYOn_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/865155343084535812/1511000429"
        },
        {
            "name": "Marco Pérez #666 #TUCAM",
            "screen_name": "msylvestre66",
            "description": "No soy dueño de la verdad absoluta. Odio la mentira y la traición. Mi repulsión por amlo es placentera. Si eres solovino, y entras aquí, es bajo tu riesgo.",
            "location": "México City",
            "protected": false,
            "followers_count": 1342,
            "friends_count": 1067,
            "created_at": "Mon May 24 23:15:38 +0000 2010",
            "favourites_count": 10684,
            "verified": false,
            "statuses_count": 61295,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/950418570755715072/390sjVV3_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/147743799/1506917564"
        },
        {
            "name": "Hip-Hop 411",
            "screen_name": "hh411tv",
            "description": "Pushing the culture forward • #WitnessTheDopeness • SA Hip Hop Awards Nominee - Kings of Gauteng 2017 •  business: info@hiphop411.tv",
            "location": "Johannesburg, South Africa",
            "protected": false,
            "followers_count": 447,
            "friends_count": 327,
            "created_at": "Tue May 24 11:46:26 +0000 2016",
            "favourites_count": 395,
            "verified": false,
            "statuses_count": 1941,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/929601231881940992/p0DFZaqZ_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/735074473934782465/1500529235"
        },
        {
            "name": "Bilgin Kaya",
            "screen_name": "bilginkaya1975",
            "description": "mechanicalengineer",
            "location": "",
            "protected": false,
            "followers_count": 395,
            "friends_count": 932,
            "created_at": "Mon Apr 14 19:16:08 +0000 2014",
            "favourites_count": 3972,
            "verified": false,
            "statuses_count": 1681,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/949047894195175425/D8F72xdw_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/2484821013/1397503090"
        },
        {
            "name": "MisterGuhh",
            "screen_name": "TheMisterGuhh",
            "description": "(YouTuber) Com o Sonho de Chegar a 100k 😍😍",
            "location": "Brasil",
            "protected": false,
            "followers_count": 378,
            "friends_count": 1607,
            "created_at": "Fri Feb 24 12:55:16 +0000 2017",
            "favourites_count": 127,
            "verified": false,
            "statuses_count": 60,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/944693478960893954/o2Ub_Nyp_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/835110849664659459/1493934085"
        },
        {
            "name": "TMonroe",
            "screen_name": "Back2Me89",
            "description": "Life is what you make it",
            "location": "",
            "protected": false,
            "followers_count": 313,
            "friends_count": 993,
            "created_at": "Sun Jul 14 11:58:42 +0000 2013",
            "favourites_count": 542,
            "verified": false,
            "statuses_count": 2352,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/829121830988423169/uCBsRTXX_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1593249985/1373803881"
        },
        {
            "name": "Dr Sania",
            "screen_name": "DrSania3",
            "description": "Born to LauGh😀Social ActivisT🙌Mano BiLLi🐱\nLove To Live in My Own WorLd😌😋\nMadly iN Love With @SidharthM💜😍",
            "location": "Faisalabad",
            "protected": false,
            "followers_count": 218,
            "friends_count": 664,
            "created_at": "Mon Apr 10 17:30:37 +0000 2017",
            "favourites_count": 175,
            "verified": false,
            "statuses_count": 242,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/916232490435710976/_mGdlbUU_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/851487594336661506/1495359131"
        },
        {
            "name": "Gilberto Horcasitas",
            "screen_name": "Giloforo",
            "description": "Nací, jugue americano, crecí, jugué americano, me titule, me casé, tengo una hija y hasta ahí voy. Experto en atención a clientes. CCE Customer Care Expert.",
            "location": "México DF",
            "protected": false,
            "followers_count": 207,
            "friends_count": 540,
            "created_at": "Sat Feb 20 13:13:08 +0000 2010",
            "favourites_count": 2071,
            "verified": false,
            "statuses_count": 3478,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/920145993680568320/gGhhXIuf_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/115923538/1427391956"
        },
        {
            "name": "Ryan Setiawan",
            "screen_name": "HiRyans",
            "description": "Graphic Design | Illustration.\nSocially Awkward.\n📧 contact.hilena@gmail.com",
            "location": "Indonesia",
            "protected": false,
            "followers_count": 193,
            "friends_count": 236,
            "created_at": "Wed May 12 14:36:02 +0000 2010",
            "favourites_count": 169,
            "verified": false,
            "statuses_count": 104,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/922741366815301632/yFVHgcCG_400x400.jpg"
        },
        {
            "name": "evan 🍫",
            "screen_name": "EvanCupid000",
            "description": "make the right choices kids, win some ,loose some, most importantly, you'll live to fight another day🤸.         ♊",
            "location": "Cape Town, South Africa",
            "protected": false,
            "followers_count": 171,
            "friends_count": 431,
            "created_at": "Sat Feb 01 13:05:29 +0000 2014",
            "favourites_count": 3346,
            "verified": false,
            "statuses_count": 694,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/949316848084013057/trXbCpJF_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/2318066631/1515930168"
        },
        {
            "name": "Shera Mae Bacarisas",
            "screen_name": "bangtanjuls",
            "description": "I'M a solid army for life. I love BTS so much because they stan us(their fans) back. We love them because they are KINGS and LEGENDS. We will stay by their side",
            "location": "Cebu",
            "protected": false,
            "followers_count": 145,
            "friends_count": 1272,
            "created_at": "Fri Jan 12 00:06:29 +0000 2018",
            "favourites_count": 245,
            "verified": false,
            "statuses_count": 326,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/951610816100315137/b7ec_-yh_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/951606267801321472/1515807014"
        },
        {
            "name": "JAKE RIVETTE",
            "screen_name": "jakey_poo715",
            "description": "Just creating the path ima walk forever! follow me on insta -Mr.Rivette! 3 month old daughter Shannon Mae! Owner of Scion Fr-s! Pictures and videos traveling!",
            "location": "kenosha, wi",
            "protected": false,
            "followers_count": 137,
            "friends_count": 1075,
            "created_at": "Thu Jan 12 04:04:31 +0000 2017",
            "favourites_count": 439,
            "verified": false,
            "statuses_count": 253,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/913148486446669824/v4F3oW9E_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/819394603765956609/1484347261"
        },
        {
            "name": "澳門氣球派對Macau Balloon",
            "screen_name": "MacauBalloon",
            "description": "澳門氣球派對 Macau Balloon Party, 澳門氣球佈置專門店 \n提供各式澳門氣球服務\n畢業氣球,生日會氣球, 百日宴佈置\n求婚氣球佈置。澳門酒店房氣球佈置\n澳門印刷宣傳氣球,澳門生日會,滿月,派對等氣球佈置,氣球禮物包裝,澳門扭氣球",
            "location": "澳門",
            "protected": false,
            "followers_count": 128,
            "friends_count": 1131,
            "created_at": "Sun Jun 25 16:38:20 +0000 2017",
            "favourites_count": 143,
            "verified": false,
            "statuses_count": 158,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/879017152442908672/xaP9T-rm_400x400.jpg"
        },
        {
            "name": "Ida Wadda",
            "screen_name": "ida_wadda",
            "description": "In pursuit of health, wealth and happiness.",
            "location": "Kampala",
            "protected": false,
            "followers_count": 116,
            "friends_count": 457,
            "created_at": "Mon Jan 09 07:07:03 +0000 2012",
            "favourites_count": 4,
            "verified": false,
            "statuses_count": 214,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/378800000039800759/4e4cc2cbbb7ad8e1118750bdef590878_400x400.jpg"
        },
        {
            "name": "~",
            "screen_name": "iVIN0TH",
            "description": "Unproven Genius",
            "location": "Bengaluru South, India",
            "protected": false,
            "followers_count": 70,
            "friends_count": 797,
            "created_at": "Thu Oct 24 10:29:12 +0000 2013",
            "favourites_count": 51,
            "verified": false,
            "statuses_count": 842,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/947359763016269824/gJ_5IOlf_400x400.jpg"
        },
        {
            "name": "Informaticaygadgets",
            "screen_name": "informatigadget",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 69,
            "friends_count": 55,
            "created_at": "Fri Mar 18 10:59:06 +0000 2016",
            "favourites_count": 115,
            "verified": false,
            "statuses_count": 132,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/710782878343405569/vjZ5q-BY_400x400.jpg"
        },
        {
            "name": "Desaizon",
            "screen_name": "desaizon",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 53,
            "friends_count": 1342,
            "created_at": "Sun Oct 15 23:19:52 +0000 2017",
            "favourites_count": 7,
            "verified": false,
            "statuses_count": 21,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/942725060875472896/dNJwTfSu_400x400.jpg"
        },
        {
            "name": "taha bauomi",
            "screen_name": "BauomiTaha",
            "description": "الثقه بالله وبعد الثقه بالنفس",
            "location": "المنيا, مصر",
            "protected": false,
            "followers_count": 49,
            "friends_count": 270,
            "created_at": "Tue Jan 09 09:42:03 +0000 2018",
            "favourites_count": 83,
            "verified": false,
            "statuses_count": 6,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/950670550510260224/UORmvtX9_400x400.jpg"
        },
        {
            "name": "yPedruuh #SBR200K",
            "screen_name": "zDarck1K",
            "description": "Pedrinho🈲 • 11y💗 • YouTuber GM✝️ • Aquario♒️ • 06 February 🎉🎊 • Pernambucano",
            "location": "Vidaloka",
            "protected": false,
            "followers_count": 38,
            "friends_count": 253,
            "created_at": "Tue Sep 12 20:56:38 +0000 2017",
            "favourites_count": 1442,
            "verified": false,
            "statuses_count": 348,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953265811380166657/E9xXfchb_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/907709560907075585/1516111714"
        },
        {
            "name": "Denise Davis ( carrie davis )",
            "screen_name": "misskandylady40",
            "description": "special needs aide for Spotsylvania county transportation! mom of two beautiful daughters 19&7...",
            "location": "Fredericksburg va",
            "protected": false,
            "followers_count": 35,
            "friends_count": 202,
            "created_at": "Tue Oct 14 19:30:29 +0000 2014",
            "favourites_count": 300,
            "verified": false,
            "statuses_count": 242,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/949080283030016001/fDRmUwjA_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/2830207708/1515113348"
        },
        {
            "name": "Creativehorns",
            "screen_name": "Creativehorns",
            "description": "Helping People in IT.",
            "location": "Ranchi, Jharkhand",
            "protected": true,
            "followers_count": 26,
            "friends_count": 53,
            "created_at": "Fri Oct 23 04:46:06 +0000 2009",
            "favourites_count": 5,
            "verified": false,
            "statuses_count": 1703,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/3132485084/01db29f079459d058b051fcce8fb5be3_400x400.jpg"
        },
        {
            "name": "Paloma Gundersen",
            "screen_name": "osornio_chavez",
            "description": "Criaturita del señorr💥 ElrubiusOMG...\nTwenty Øne Piløts |-/ \nMarshall Bruce Mathers➡EMINƎM\nFCBarcelona⚽\n🎮🦄",
            "location": "México",
            "protected": false,
            "followers_count": 25,
            "friends_count": 132,
            "created_at": "Sat Dec 16 03:40:13 +0000 2017",
            "favourites_count": 1029,
            "verified": false,
            "statuses_count": 35,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953281477499916289/tDP4NRKF_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/941875586506649601/1516141538"
        },
        {
            "name": "ATHEER KHAMEES",
            "screen_name": "AtheerKhamees",
            "description": "",
            "location": "Iraq",
            "protected": false,
            "followers_count": 20,
            "friends_count": 394,
            "created_at": "Sun Jan 07 19:53:16 +0000 2018",
            "favourites_count": 24,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/951477566010986498/KDZrK9Zh_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/950092994396545029/1515684953"
        },
        {
            "name": "JAMIAHAMDARD ALUMNI",
            "screen_name": "Hamdarduniversi",
            "description": "Sarfaraz Nawaz Former President Students Union Jamia Hamdard University New Delhi. The Official Twitter Account of the Alumni of Jamia Hamdard University Ind",
            "location": "New Delhi India",
            "protected": false,
            "followers_count": 20,
            "friends_count": 524,
            "created_at": "Fri Sep 15 08:52:38 +0000 2017",
            "favourites_count": 140,
            "verified": false,
            "statuses_count": 33,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/908617208871321600/BrYLA4aj_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/908614522256072705/1505924606"
        },
        {
            "name": "Cgal",
            "screen_name": "ESTEE_GOOSSENS",
            "description": "Seagal",
            "location": "Brussels, Belgium",
            "protected": false,
            "followers_count": 16,
            "friends_count": 69,
            "created_at": "Tue Mar 22 12:06:58 +0000 2016",
            "favourites_count": 1693,
            "verified": false,
            "statuses_count": 25,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/889450760483872770/Pi2c6dX8_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/712249204425564161/1500896588"
        },
        {
            "name": "Yasmin Ramos",
            "screen_name": "Yasmin39242081",
            "description": "Aquáriana♒ Bi❤",
            "location": "",
            "protected": false,
            "followers_count": 12,
            "friends_count": 175,
            "created_at": "Tue Jan 16 16:27:00 +0000 2018",
            "favourites_count": 11,
            "verified": false,
            "statuses_count": 88,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953465393309417473/0m3cAgPi_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/953302575054499840/1516120299"
        },
        {
            "name": "Essential Steve",
            "screen_name": "Exential",
            "description": "Daring",
            "location": "Big City",
            "protected": false,
            "followers_count": 11,
            "friends_count": 1253,
            "created_at": "Tue Nov 03 09:32:02 +0000 2009",
            "favourites_count": 1,
            "verified": false,
            "statuses_count": 89,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/442876737513594880/oIpS2sPA_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/87152760/1516201889"
        },
        {
            "name": "hannah",
            "screen_name": "hannahrenae0",
            "description": "a history of bad decisions :(:",
            "location": "Key West, FL",
            "protected": false,
            "followers_count": 11,
            "friends_count": 46,
            "created_at": "Tue Jan 16 15:35:45 +0000 2018",
            "favourites_count": 16,
            "verified": false,
            "statuses_count": 12,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953291268238569472/SY2PSRv2_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/953289678320537600/1516118415"
        },
        {
            "name": "Patricia Doiron",
            "screen_name": "PatriciaDoiron3",
            "description": "I have questions...",
            "location": "Montréal, Québec",
            "protected": false,
            "followers_count": 10,
            "friends_count": 141,
            "created_at": "Wed Dec 05 18:09:07 +0000 2012",
            "favourites_count": 136,
            "verified": false,
            "statuses_count": 14,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Majedi AI-goraadi",
            "screen_name": "Hgg4bHtW1onN2jl",
            "description": "‏‏‏كُن مختلفاً كَ أمير ☺ . 💙",
            "location": "",
            "protected": false,
            "followers_count": 10,
            "friends_count": 141,
            "created_at": "Mon Dec 04 16:28:14 +0000 2017",
            "favourites_count": 42,
            "verified": false,
            "statuses_count": 2,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/944337217190842368/u7z1wDfS_400x400.jpg"
        },
        {
            "name": "The Lanky Ghost👻",
            "screen_name": "thelankyghost",
            "description": "YouTube// thelankyghost • Check it out for competitive Call of Duty content • Along side other games! \n(Hit me up if you are a small youtuber and play Xbox!)",
            "location": "",
            "protected": false,
            "followers_count": 9,
            "friends_count": 113,
            "created_at": "Tue Jan 02 11:31:33 +0000 2018",
            "favourites_count": 97,
            "verified": false,
            "statuses_count": 25,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/948157626554245120/J-zGZ1LN_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/948154794342051840/1515015637"
        },
        {
            "name": "korfjeee",
            "screen_name": "America_Warior",
            "description": "ik ben joshua en maak voor de lol YT filmpjes",
            "location": "Velsen, Nederland",
            "protected": false,
            "followers_count": 9,
            "friends_count": 36,
            "created_at": "Thu Mar 30 15:03:42 +0000 2017",
            "favourites_count": 393,
            "verified": false,
            "statuses_count": 41,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953647477189742592/bETuAXK__400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/847464355926908928/1516202237"
        },
        {
            "name": "Eclectic Radio",
            "screen_name": "EclecticRadio17",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 9,
            "friends_count": 99,
            "created_at": "Tue May 02 23:36:54 +0000 2017",
            "favourites_count": 5,
            "verified": false,
            "statuses_count": 74,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/860149619208069120/B54vay32_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/859552308945977346/1493910644"
        },
        {
            "name": "Nader Galal",
            "screen_name": "NaderGalal05",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 8,
            "friends_count": 101,
            "created_at": "Fri Sep 29 10:10:55 +0000 2017",
            "favourites_count": 6,
            "verified": false,
            "statuses_count": 1,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "D19Anhduc",
            "screen_name": "D19Anhduc",
            "description": "Tiền đạo của ĐT Pháp và CLB Manchester United",
            "location": "Hà Nội, Việt Nam",
            "protected": false,
            "followers_count": 8,
            "friends_count": 56,
            "created_at": "Sun Dec 31 13:08:23 +0000 2017",
            "favourites_count": 88,
            "verified": false,
            "statuses_count": 1,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/951477990776438784/I041o_20_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/947454388171243520/1515749132"
        },
        {
            "name": "Akmal Agha",
            "screen_name": "agaakmal",
            "description": "",
            "location": "Tysons Corner, VA",
            "protected": false,
            "followers_count": 8,
            "friends_count": 268,
            "created_at": "Thu Jan 12 04:22:36 +0000 2017",
            "favourites_count": 46,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/951277785129111552/FXabqbuq_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/819399153558188032/1515637271"
        },
        {
            "name": "Sidinho António Muandama",
            "screen_name": "AntonioSidinho",
            "description": "A VERDADE DIVINA",
            "location": "República de Moçambique",
            "protected": false,
            "followers_count": 7,
            "friends_count": 168,
            "created_at": "Sun Jan 07 16:49:00 +0000 2018",
            "favourites_count": 2,
            "verified": false,
            "statuses_count": 6,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/950047855162675200/3WeDtr00_400x400.jpg"
        },
        {
            "name": "Btsofficial.Latino",
            "screen_name": "BtsofficialLat1",
            "description": "fighting!!",
            "location": "",
            "protected": false,
            "followers_count": 6,
            "friends_count": 74,
            "created_at": "Tue Jan 16 02:31:24 +0000 2018",
            "favourites_count": 2,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953093896904630273/gucCywMx_400x400.jpg"
        },
        {
            "name": "Das Zoccablümschen",
            "screen_name": "Dasbluemschen",
            "description": "#Survivalist / kleiner #Youtuber/ total verpeilt, aber immer mit #Fun und Crazyness bei der Sache ^^ https://www.youtube.com/channel/UCuBU-NnkH0SHeMA85YFOlYQ",
            "location": "",
            "protected": false,
            "followers_count": 5,
            "friends_count": 38,
            "created_at": "Fri Jun 02 12:05:14 +0000 2017",
            "favourites_count": 64,
            "verified": false,
            "statuses_count": 234,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/870616047283576832/ofHgr4zV_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/870612267624214529/1496406014"
        },
        {
            "name": "Swe Amarante",
            "screen_name": "AmaranteSwe",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 4,
            "friends_count": 85,
            "created_at": "Wed Jan 03 20:25:22 +0000 2018",
            "favourites_count": 15,
            "verified": false,
            "statuses_count": 4,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/948653882774900737/UjNpEdL7_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/948651522757447682/1515107969"
        },
        {
            "name": "Ajay kurrey",
            "screen_name": "Ajay57752879",
            "description": "I love techical world",
            "location": "Bhilai Sector 2, Bhilai",
            "protected": false,
            "followers_count": 4,
            "friends_count": 13,
            "created_at": "Fri Nov 17 07:52:43 +0000 2017",
            "favourites_count": 34,
            "verified": false,
            "statuses_count": 24,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/931431454323523584/22dttxjG_400x400.jpg"
        },
        {
            "name": "Nikos Kousettis",
            "screen_name": "kousettis",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 4,
            "friends_count": 21,
            "created_at": "Fri Mar 21 12:00:04 +0000 2014",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/446979755574067200/Z07r2eQh_400x400.jpg"
        },
        {
            "name": "AHHHHHH",
            "screen_name": "kermdoid",
            "description": "the godfather has nothing on home alone 3",
            "location": "United Kingdom",
            "protected": true,
            "followers_count": 4,
            "friends_count": 70,
            "created_at": "Tue Jun 13 17:28:17 +0000 2017",
            "favourites_count": 383,
            "verified": false,
            "statuses_count": 122,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/876160105703776260/GpEwwFF1_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/874679831404924928/1497375113"
        },
        {
            "name": "Andre Hutchinson",
            "screen_name": "AndreHutchins17",
            "description": "Make the most of my life",
            "location": "",
            "protected": false,
            "followers_count": 3,
            "friends_count": 165,
            "created_at": "Wed Jan 17 13:46:58 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953628292023816192/WLvQOck5_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/953624688487526400/1516197675"
        },
        {
            "name": "joão victor",
            "screen_name": "joaovictorTV3",
            "description": "eu sou joao gosto de gravar video",
            "location": "ara",
            "protected": false,
            "followers_count": 3,
            "friends_count": 80,
            "created_at": "Fri Jan 12 00:58:37 +0000 2018",
            "favourites_count": 7,
            "verified": false,
            "statuses_count": 11,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/951620868802797569/T_eiB6KN_400x400.jpg"
        },
        {
            "name": "issam hassan",
            "screen_name": "issam957",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 2,
            "friends_count": 23,
            "created_at": "Fri Feb 25 02:04:46 +0000 2011",
            "favourites_count": 44,
            "verified": false,
            "statuses_count": 8,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Hasan Imam",
            "screen_name": "ImamHasan252",
            "description": "",
            "location": "Patna, Bihar",
            "protected": true,
            "followers_count": 2,
            "friends_count": 36,
            "created_at": "Tue May 29 06:35:48 +0000 2012",
            "favourites_count": 245,
            "verified": false,
            "statuses_count": 70,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/923486137187844096/98tUQ-QG_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/593438389/1515848278"
        },
        {
            "name": "Brandie",
            "screen_name": "Brandie40546196",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 2,
            "friends_count": 87,
            "created_at": "Mon Jan 15 09:15:30 +0000 2018",
            "favourites_count": 1,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Shãshì Dhãr R(Róçky)",
            "screen_name": "ShshDhrR1",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 2,
            "friends_count": 63,
            "created_at": "Wed Jan 17 09:13:03 +0000 2018",
            "favourites_count": 21,
            "verified": false,
            "statuses_count": 1,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953568199525638146/4CXo3J5T_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/953555757630242816/1516181352"
        },
        {
            "name": "Korri Vittal",
            "screen_name": "KorriVittal1",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 2,
            "friends_count": 98,
            "created_at": "Wed Jan 17 15:19:46 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Doaa",
            "screen_name": "Doaa81086288",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 2,
            "friends_count": 60,
            "created_at": "Sun Jan 14 22:03:22 +0000 2018",
            "favourites_count": 1,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/952668571095707649/cgQBqvIW_400x400.jpg"
        },
        {
            "name": "blacksweet17",
            "screen_name": "blckswt17",
            "description": "",
            "location": "Gresik, Jawa Timur",
            "protected": false,
            "followers_count": 2,
            "friends_count": 16,
            "created_at": "Wed Jan 17 14:52:31 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953642246993096705/LFgFfCoo_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/953641184756359168/1516201023"
        },
        {
            "name": "Fardin Sedeqi",
            "screen_name": "SedeqiFardin",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 1,
            "friends_count": 119,
            "created_at": "Wed Jan 17 15:17:02 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953648709790822400/Z4m26XEn_400x400.jpg"
        },
        {
            "name": "milan",
            "screen_name": "Milan_sayavong9",
            "description": "",
            "location": "Leesburg, FL",
            "protected": true,
            "followers_count": 1,
            "friends_count": 108,
            "created_at": "Wed Jan 17 13:31:20 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953621941881098240/jTEwvlbw_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/953620758336589824/1516196186"
        },
        {
            "name": "Diário de uma jovem carismática",
            "screen_name": "Diriodeumajove1",
            "description": "As aventuras de uma jovem católica, e tudo que enfrenta na igreja ♥️ \nMaria não está morta ❣️",
            "location": "",
            "protected": false,
            "followers_count": 1,
            "friends_count": 15,
            "created_at": "Wed Jan 17 15:02:42 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953647759915089921/RFS3ijO9_400x400.jpg"
        },
        {
            "name": "Martyna Kraska",
            "screen_name": "KraskaMartix7",
            "description": "Always be yourself",
            "location": "Polska",
            "protected": false,
            "followers_count": 1,
            "friends_count": 61,
            "created_at": "Fri May 30 17:12:54 +0000 2014",
            "favourites_count": 10,
            "verified": false,
            "statuses_count": 1,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953646544057716736/_D0ESSAL_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/2535509528/1516202026"
        },
        {
            "name": "رحمه البلوي",
            "screen_name": "r7oom5g",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 1,
            "friends_count": 42,
            "created_at": "Wed Jan 17 15:20:15 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Shyuhadahshyu",
            "screen_name": "shyuhadahshyu",
            "description": "",
            "location": "",
            "protected": true,
            "followers_count": 1,
            "friends_count": 30,
            "created_at": "Wed Jan 17 15:20:22 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Ojas Srivastava",
            "screen_name": "Ojas1807",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 1,
            "friends_count": 6,
            "created_at": "Thu Jan 11 05:27:47 +0000 2018",
            "favourites_count": 10,
            "verified": false,
            "statuses_count": 1,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Susanto0779@mail",
            "screen_name": "susanto0779",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 1,
            "friends_count": 32,
            "created_at": "Thu Jan 04 01:05:21 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Hanif Sikdar",
            "screen_name": "HanifSikdar9",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 1,
            "friends_count": 11,
            "created_at": "Sun Dec 31 03:32:43 +0000 2017",
            "favourites_count": 10,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Elliot",
            "screen_name": "Elliot67719647",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 1,
            "friends_count": 20,
            "created_at": "Wed Jan 17 15:21:04 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "二階 トモキ",
            "screen_name": "lHWqQJF9AQ4KsX5",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 1,
            "friends_count": 21,
            "created_at": "Wed Jan 17 15:18:57 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Kongyuguan",
            "screen_name": "kongyuguan",
            "description": "",
            "location": "",
            "protected": true,
            "followers_count": 1,
            "friends_count": 18,
            "created_at": "Fri May 15 14:46:03 +0000 2015",
            "favourites_count": 3,
            "verified": false,
            "statuses_count": 4,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/950664451929378817/czey6-9K_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/3196425554/1431794810"
        },
        {
            "name": "Mohamad Majed Murad",
            "screen_name": "MohamadMu1",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 1,
            "friends_count": 11,
            "created_at": "Thu Jun 02 14:06:51 +0000 2016",
            "favourites_count": 8,
            "verified": false,
            "statuses_count": 1,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Edgar Dahl Meza",
            "screen_name": "DahlMeza",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 1,
            "friends_count": 58,
            "created_at": "Wed Jan 17 15:16:42 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Rakesh",
            "screen_name": "Rakesh82800354",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 1,
            "friends_count": 122,
            "created_at": "Wed Jan 17 15:14:50 +0000 2018",
            "favourites_count": 1,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "ليان",
            "screen_name": "al_e3k",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 43,
            "created_at": "Wed Jan 17 15:18:37 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 6,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953648088757030913/eZ5SIqMm_400x400.jpg"
        },
        {
            "name": "ぶるんぶる",
            "screen_name": "hoyqkwhm415",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 94,
            "created_at": "Wed Jan 17 15:17:17 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "بنرنبنبتبتيتيايااي",
            "screen_name": "9XRJd19ZunnhFtY",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 20,
            "created_at": "Wed Jan 17 15:18:50 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "HAIKAL@GMAIL.COM",
            "screen_name": "HAIKALGMAILCOM6",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 1,
            "created_at": "Wed Jan 17 15:19:18 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Hasjub We",
            "screen_name": "HasjubW",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 44,
            "created_at": "Wed Jan 17 14:44:58 +0000 2018",
            "favourites_count": 3,
            "verified": false,
            "statuses_count": 1,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Partyanimalthe6th",
            "screen_name": "Partyanimalthe1",
            "description": "Live life to the fullest",
            "location": "United States",
            "protected": false,
            "followers_count": 0,
            "friends_count": 5,
            "created_at": "Tue Jan 02 04:45:46 +0000 2018",
            "favourites_count": 4,
            "verified": false,
            "statuses_count": 13,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/948061563822342144/sELINkiV_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/948052673189724160/1514870465"
        },
        {
            "name": "المطنوخ",
            "screen_name": "aMz2ZFE3aXaVZIA",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 20,
            "created_at": "Wed Jan 17 15:19:54 +0000 2018",
            "favourites_count": 3,
            "verified": false,
            "statuses_count": 3,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Martins-Ninjel",
            "screen_name": "MartinsNinjel",
            "description": "Vc saber que eu sou um cara Bacana 😍",
            "location": "Manaus, Brasil",
            "protected": false,
            "followers_count": 0,
            "friends_count": 40,
            "created_at": "Tue Jan 16 21:55:08 +0000 2018",
            "favourites_count": 8,
            "verified": false,
            "statuses_count": 2,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953387967040630784/dKZuPhU9_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/953385152515854342/1516140377"
        },
        {
            "name": "kuldeep mann",
            "screen_name": "KuldeepMann348",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 84,
            "created_at": "Wed Jan 17 15:19:02 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "nncxxxjgx",
            "screen_name": "nncxxxjgx",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 41,
            "created_at": "Wed Jan 17 15:20:37 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Carlos Eduardo",
            "screen_name": "duduzotaac",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 32,
            "created_at": "Sat Nov 04 00:15:03 +0000 2017",
            "favourites_count": 32,
            "verified": false,
            "statuses_count": 16,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "刘子乾",
            "screen_name": "yWtjAhrOLxEib89",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 14,
            "created_at": "Wed Jan 17 14:58:22 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Camila Veloso",
            "screen_name": "CamilaV32467472",
            "description": "Gosto de sorrisos que me fazem sorrir 😘",
            "location": "Fortaleza, Brasil",
            "protected": false,
            "followers_count": 0,
            "friends_count": 19,
            "created_at": "Wed Jan 17 15:07:26 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953647233387417605/Nu8Ln4p3_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/953644941510676480/1516202191"
        },
        {
            "name": "الاء",
            "screen_name": "RMfvGgqrFzlRDvL",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 1,
            "created_at": "Wed Jan 17 15:21:38 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Louie Rogers",
            "screen_name": "LouieRogers16",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 22,
            "created_at": "Wed Jan 17 15:17:22 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Malak",
            "screen_name": "Malak_designs",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 35,
            "created_at": "Wed Jan 17 15:21:04 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Phimonpaht",
            "screen_name": "phimonpaht",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 16,
            "created_at": "Mon Jan 15 15:05:14 +0000 2018",
            "favourites_count": 10,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "حيدر محمد",
            "screen_name": "fFVE0z4WkQe8zLm",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 30,
            "created_at": "Wed Jan 17 15:17:23 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Yasmin Pineda",
            "screen_name": "YasminP56166237",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 46,
            "created_at": "Wed Jan 17 03:28:44 +0000 2018",
            "favourites_count": 1,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Rowland Eveleigh",
            "screen_name": "Rowdog1235",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 10,
            "created_at": "Wed Jan 10 14:19:11 +0000 2018",
            "favourites_count": 2,
            "verified": false,
            "statuses_count": 2,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Julia",
            "screen_name": "Julia23257037",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 23,
            "created_at": "Wed Jan 17 15:20:59 +0000 2018",
            "favourites_count": 1,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "kira kiên",
            "screen_name": "kien_kira",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 94,
            "created_at": "Wed Jan 17 15:18:37 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 1,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953648535643111424/GODUeYjE_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/953647754701504512/1516202608"
        },
        {
            "name": "Поторочина Елена",
            "screen_name": "3LaWCK3meljvT4v",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 30,
            "created_at": "Wed Jan 17 15:18:21 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Brayan Arley Silva Ceron",
            "screen_name": "BrayanArleySil1",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 81,
            "created_at": "Wed Jan 17 15:22:07 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "ابوراس المهراس",
            "screen_name": "tLzsjAdwATunN08",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 86,
            "created_at": "Wed Jan 17 15:06:41 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "فواز الزهراني",
            "screen_name": "AUYk4xDMicnUnid",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 42,
            "created_at": "Wed Jan 17 15:16:26 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Ismael Blando",
            "screen_name": "IsmaelBlando",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 39,
            "created_at": "Sun Sep 17 03:24:36 +0000 2017",
            "favourites_count": 4,
            "verified": false,
            "statuses_count": 2,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Om Ahmad",
            "screen_name": "OmAhmad31032044",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 11,
            "created_at": "Sat Nov 18 15:44:55 +0000 2017",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/947956746332581889/oDvAVyuT_400x400.jpg"
        },
        {
            "name": "hassan Waid",
            "screen_name": "WaidHassan",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 45,
            "created_at": "Wed Jan 17 10:42:44 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Hamsafar",
            "screen_name": "Hamsafa32730374",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 20,
            "created_at": "Wed Jan 17 15:22:32 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "Cleriaton matos",
            "screen_name": "CleristonMats",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 46,
            "created_at": "Wed Jan 17 15:19:47 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        },
        {
            "name": "MOSARUB360",
            "screen_name": "mosarub360",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 66,
            "created_at": "Wed Jan 17 15:17:20 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 1,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/953648023506010112/LJFCLvMW_400x400.jpg"
        },
        {
            "name": "سلطان",
            "screen_name": "nSbTVhnn5XKqBia",
            "description": "",
            "location": "",
            "protected": false,
            "followers_count": 0,
            "friends_count": 35,
            "created_at": "Wed Jan 17 15:22:06 +0000 2018",
            "favourites_count": 0,
            "verified": false,
            "statuses_count": 0,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.jpg"
        }
    ],
    "usersFriends": [
        {
            "name": "Kevin Durant",
            "screen_name": "KDTrey5",
            "description": "IM ME, I DO ME, AND I CHILL",
            "location": "At the crib dog",
            "protected": false,
            "followers_count": 17409174,
            "friends_count": 1456,
            "created_at": "Tue Apr 28 01:14:36 +0000 2009",
            "favourites_count": 91,
            "verified": true,
            "statuses_count": 23164,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/889585901222989825/gp_fGcQ5_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/35936474/1500928779"
        },
        {
            "name": "Variety",
            "screen_name": "Variety",
            "description": "The business of entertainment.",
            "location": "Los Angeles, CA",
            "protected": false,
            "followers_count": 2056545,
            "friends_count": 287412,
            "created_at": "Thu Nov 20 23:02:29 +0000 2008",
            "favourites_count": 337,
            "verified": true,
            "statuses_count": 202017,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/718457704189001728/xN83wlqp_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/17525171/1516137702"
        },
        {
            "name": "Sundar Pichai",
            "screen_name": "sundarpichai",
            "description": "CEO, @google",
            "location": "",
            "protected": false,
            "followers_count": 1568981,
            "friends_count": 317,
            "created_at": "Wed Mar 12 05:51:53 +0000 2008",
            "favourites_count": 639,
            "verified": true,
            "statuses_count": 1068,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/864282616597405701/M-FEJMZ0_400x400.jpg"
        },
        {
            "name": "Demi Lovato News",
            "screen_name": "DLovatoNews",
            "description": "The official http://DemiLovato.org's twitter, we provide lovatics all the recent news & updates on Demi Lovato.",
            "location": "Singapore",
            "protected": false,
            "followers_count": 224611,
            "friends_count": 222,
            "created_at": "Fri Mar 27 10:19:57 +0000 2009",
            "favourites_count": 83,
            "verified": false,
            "statuses_count": 4240,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/924828800667361280/rvNadLPh_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/26980410/1509331363"
        },
        {
            "name": "Demi Lovato News",
            "screen_name": "OurGirlDemetria",
            "description": "Daily updates on everything Demi Lovato! Get Demi's new album #TellMeYouLoveMe out now: http://smarturl.it/TMYLMiTunes",
            "location": "Trinidad & Tobago ",
            "protected": false,
            "followers_count": 221349,
            "friends_count": 168,
            "created_at": "Wed Nov 11 03:53:04 +0000 2009",
            "favourites_count": 4134,
            "verified": false,
            "statuses_count": 133159,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/923639334036824064/G2jtyyGE_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/89101082/1509078845"
        },
        {
            "name": "Demi Lovato",
            "screen_name": "TeamDemiLovato",
            "description": "TELL ME YOU LOVE ME OUT NOW!",
            "location": "United Kingdom",
            "protected": false,
            "followers_count": 206877,
            "friends_count": 436,
            "created_at": "Fri Oct 16 06:00:35 +0000 2009",
            "favourites_count": 2430,
            "verified": false,
            "statuses_count": 208900,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/949939124139634688/4a-qYfqD_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/82811968/1515318112"
        },
        {
            "name": "MoonPie",
            "screen_name": "MoonPie",
            "description": "We make delicious MoonPies for everyone to enjoy even you",
            "location": "Chattanooga, TN",
            "protected": false,
            "followers_count": 179426,
            "friends_count": 5567,
            "created_at": "Mon Nov 02 18:03:52 +0000 2009",
            "favourites_count": 9809,
            "verified": true,
            "statuses_count": 6700,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/418783559751839744/R-RIDHrc_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/86993064/1515010206"
        },
        {
            "name": "WHAT'S INSIDE?",
            "screen_name": "whatsinside",
            "description": "Curiosity, Fun, educational and weird videos on the internet.",
            "location": "",
            "protected": false,
            "followers_count": 125949,
            "friends_count": 192,
            "created_at": "Sun Jun 07 22:46:27 +0000 2015",
            "favourites_count": 19740,
            "verified": true,
            "statuses_count": 3798,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/607683265453948928/vitaUD07_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/3239203002/1433718239"
        },
        {
            "name": "bill wurtz",
            "screen_name": "billwurtz",
            "description": "is self",
            "location": "billwurtz.com",
            "protected": false,
            "followers_count": 123111,
            "friends_count": 96,
            "created_at": "Fri Apr 29 09:57:13 +0000 2011",
            "favourites_count": 26603,
            "verified": true,
            "statuses_count": 2579,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/476792893844115457/zzIv5wiU_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/289853473/1435339266"
        },
        {
            "name": "Demi Lovato News",
            "screen_name": "demetriaaalove",
            "description": "New album “Tell Me You Love Me” is out now! Watch the documentary #SimplyComplicated. Demi x DJ Khaled 2018 tour coming soon!",
            "location": "",
            "protected": false,
            "followers_count": 120552,
            "friends_count": 46303,
            "created_at": "Thu Jul 28 04:38:27 +0000 2011",
            "favourites_count": 4321,
            "verified": false,
            "statuses_count": 29188,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/925527354763612161/Q6WpW7sv_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/343836872/1510536239"
        },
        {
            "name": "Portal Katy Perry",
            "screen_name": "portalkatyperry",
            "description": "Official twitter of the best fansite about Katy Perry. http://KatyGallery.com \nContato: portalkatyperry@hotmail.com",
            "location": "Brasil",
            "protected": false,
            "followers_count": 86935,
            "friends_count": 124,
            "created_at": "Tue Jun 15 19:18:51 +0000 2010",
            "favourites_count": 1438,
            "verified": false,
            "statuses_count": 30675,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/940996054635466752/QeY_4B2o_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/156004026/1513185853"
        },
        {
            "name": "Anchorage Daily News",
            "screen_name": "adndotcom",
            "description": "Alaska's largest news site and newspaper. (Formerly Alaska Dispatch News) Newstips@adn.com or call 907-257-4301.",
            "location": "Anchorage, Alaska",
            "protected": false,
            "followers_count": 69817,
            "friends_count": 6116,
            "created_at": "Tue Aug 12 20:59:03 +0000 2008",
            "favourites_count": 211,
            "verified": true,
            "statuses_count": 49667,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/932121310108442624/NY7s0rqO_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/15828025/1458879223"
        },
        {
            "name": "Katy Perry Daily",
            "screen_name": "kpdaily",
            "description": "Katy Perry Daily is a fansite about American singer/songwriter @katyperry!\nContact: katyperrydotcom@gmail.com",
            "location": "Europe",
            "protected": false,
            "followers_count": 56644,
            "friends_count": 250,
            "created_at": "Sun Apr 25 16:55:32 +0000 2010",
            "favourites_count": 1981,
            "verified": false,
            "statuses_count": 14718,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/881089988720513025/PcF98dCL_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/137050655/1498903219"
        },
        {
            "name": "Missy Lynn",
            "screen_name": "missylynn",
            "description": "Air Force Veteran. Beauty/Lifestyle Content Creator. Business Inquiries: ➡️ info@mymissylynn.com ✨ Dreams do come True✨ LA ✈️ DALLAS Instagram: @missylynn",
            "location": "Los Angeles, California",
            "protected": false,
            "followers_count": 46675,
            "friends_count": 1396,
            "created_at": "Wed Mar 17 03:36:37 +0000 2010",
            "favourites_count": 29,
            "verified": true,
            "statuses_count": 41002,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/928803152714969091/wVktnlaC_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/123749190/1453526854"
        },
        {
            "name": "Ohm Cocktail",
            "screen_name": "studiohmega",
            "description": "A son, a brother, a husband, a father, self-taught modeler and a singer...",
            "location": "",
            "protected": false,
            "followers_count": 46476,
            "friends_count": 71,
            "created_at": "Wed Jul 15 16:09:32 +0000 2015",
            "favourites_count": 183,
            "verified": false,
            "statuses_count": 1686,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/621351618441646081/4U2i_vHw_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/3280824355/1513424067"
        },
        {
            "name": "Roly",
            "screen_name": "RolyUnGashaa",
            "description": "LGBT+ Advocate & YouTube Video Creator living in London! 27, Non-Binary & Body Modification enthusiast 🌈 Business: rolyungashaahd@gmail.com",
            "location": "London, England",
            "protected": false,
            "followers_count": 22872,
            "friends_count": 486,
            "created_at": "Wed Oct 21 20:16:41 +0000 2009",
            "favourites_count": 32003,
            "verified": true,
            "statuses_count": 34168,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/907749648135225345/9Ea67ocj_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/84152649/1503609450"
        },
        {
            "name": "Ellen Show Me More",
            "screen_name": "EllenShowMeMore",
            "description": "Ellen DeGeneres has a brand new series on YouTube featuring more celebs, more comedy, more games, more everything! #EllenShowMeMore",
            "location": "Los Angeles, CA",
            "protected": false,
            "followers_count": 9421,
            "friends_count": 38,
            "created_at": "Thu Sep 14 02:13:32 +0000 2017",
            "favourites_count": 170,
            "verified": true,
            "statuses_count": 250,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/908157587345965056/jBFVU-TC_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/908151697335189505/1505865354"
        },
        {
            "name": "JamieTLD ⚡️",
            "screen_name": "JamieTLD",
            "description": "Vlogger, Social Maven & Aspiring Author. Founder of @snapinkapparel. LGBTQ+ Advocate. http://Youtube.com/c/theelowdown - TLDJamie@gmail.com",
            "location": "London, England",
            "protected": false,
            "followers_count": 7351,
            "friends_count": 845,
            "created_at": "Thu Jan 09 08:31:22 +0000 2014",
            "favourites_count": 29483,
            "verified": false,
            "statuses_count": 16617,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/893054095883251712/aa0IkbLf_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/2270383012/1510679854"
        },
        {
            "name": "Olly Pike",
            "screen_name": "ollypike",
            "description": "LGBT+ Advocate, Creator of @PopnOlly, Author/Illustrator of LGBT+ children's books Subscribe to http://www.youtube.com/popnolly. He/Him",
            "location": "London",
            "protected": false,
            "followers_count": 5750,
            "friends_count": 1372,
            "created_at": "Sun Jul 05 18:40:47 +0000 2009",
            "favourites_count": 6324,
            "verified": true,
            "statuses_count": 7676,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/895414483899871232/y8Hq2nOm_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/53972580/1511447476"
        },
        {
            "name": "Scott Balf",
            "screen_name": "scottbalf",
            "description": "I'm Scott. I’m alright sometimes.✌🏼",
            "location": "Farts.",
            "protected": false,
            "followers_count": 3429,
            "friends_count": 366,
            "created_at": "Tue Oct 27 23:55:25 +0000 2009",
            "favourites_count": 84313,
            "verified": false,
            "statuses_count": 121679,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/945358254376353793/P-olp8j8_400x400.jpg",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/85696640/1509581749"
        }
    ],
    "userStatuses": [
        {
            "timeStamp": "Wed Jan 17 13:36:13 +0000 2018",
            "tweetBody": "Correct. You need not be a part of YPP to use the creator features like custom thumbnails or live streaming. You just need to have a verified account (by phone): https://t.co/QwlFoZO5OP https://t.co/Xp3NcpO5F9",
            "retweet_count": 80,
            "favorite_count": 877
        },
        {
            "timeStamp": "Wed Jan 17 04:47:32 +0000 2018",
            "tweetBody": "*watches video*\n*breathing eases* \n*traumatic memories are replaced with images of dough undulating, coiling, uncoiling*\n*fears dissolve. worries fade. you can love again, but you can only love noodles.*\n*everything is going to be ok and/or noodles*\nhttps://t.co/OwNA0ncDil https://t.co/4mAKRKD5yF",
            "retweet_count": 189,
            "favorite_count": 1483
        },
        {
            "timeStamp": "Wed Jan 17 02:31:56 +0000 2018",
            "tweetBody": "NEVER LET ANYONE TELL YOU THAT CAT VIDEOS ARE STUPID https://t.co/VoQrr4PYq7",
            "retweet_count": 150,
            "favorite_count": 1308
        },
        {
            "timeStamp": "Tue Jan 16 23:03:44 +0000 2018",
            "tweetBody": "We fell into a YouTube hole and found this video of a mile-long zipline in somebody's Maine backyard. So that worked out well. https://t.co/DOUAUjxcm9",
            "retweet_count": 30,
            "favorite_count": 228
        },
        {
            "timeStamp": "Tue Jan 16 23:01:20 +0000 2018",
            "tweetBody": "it worked https://t.co/Ld4EIemq7S",
            "retweet_count": 91,
            "favorite_count": 868
        },
        {
            "timeStamp": "Tue Jan 16 22:07:08 +0000 2018",
            "tweetBody": "so how's that novel coming along https://t.co/3Qg6VeJC6H https://t.co/R03YOqcrR2",
            "retweet_count": 113,
            "favorite_count": 925
        },
        {
            "timeStamp": "Tue Jan 16 21:00:41 +0000 2018",
            "tweetBody": "#RHSolvesCrimes✅ #EscapeTheNight✅ #RLBuddySystem✅ #YTRedOriginals✅ https://t.co/OymlJEm3k5",
            "retweet_count": 55,
            "favorite_count": 590
        },
        {
            "timeStamp": "Tue Jan 16 19:07:27 +0000 2018",
            "tweetBody": "The cats couldn't get into the concert hall...so he brought the concert to the cats. \n\nWatch Fantasia dei Gatti, a new animated short set to Paganini’s Caprice No. 17 and featuring the violinist Augustin Hadelich. 🎶🎻😻 https://t.co/bBjSZ9qJXt https://t.co/kMdTkAuxSH",
            "retweet_count": 181,
            "favorite_count": 1217
        },
        {
            "timeStamp": "Tue Jan 16 17:27:08 +0000 2018",
            "tweetBody": "It's going to be one of those days. \n\nReferee loses toupee in high school basketball game ➡️ https://t.co/oU0Fj8AzBb https://t.co/RtGaC8slhc",
            "retweet_count": 182,
            "favorite_count": 971
        },
        {
            "timeStamp": "Tue Jan 16 16:41:20 +0000 2018",
            "tweetBody": "🚂🚂🚂https://t.co/ouD42C6Oyh https://t.co/1xNcsB2GEM",
            "retweet_count": 139,
            "favorite_count": 1150
        },
        {
            "timeStamp": "Tue Jan 16 15:51:28 +0000 2018",
            "tweetBody": "\"You can find out more than you ever will on Google, I swear, by actually speaking to people.\" https://t.co/KHhPDmILwp",
            "retweet_count": 78,
            "favorite_count": 1101
        }
    ]
}